-- Esta migração foi neutralizada porque o banco de dados atual já não
-- possui as estruturas antigas (Prestador/Certificado) esperadas pelo script
-- gerado anteriormente. Manter a migração vazia evita falhas no shadow database
-- durante o prisma migrate dev e preserva o histórico já aplicado em produção.
