// <auto-generated>
using System;
using API_NFSe.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API_NFSe.Infra.Data.Migrations
{
    [DbContext(typeof(ApiContext))]
    [Migration("20260209_AddBilhetagemSupport")]
    partial class AddBilhetagemSupport
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_general_ci")
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("API_NFSe.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");
                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");
                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);
                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime(6)");
                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");
                    b.Property<DateTimeOffset>("DataHora")
                        .HasColumnType("datetime(6)");
                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");
                    b.Property<string>("Ip")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");
                    b.Property<string>("Metodo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");
                    b.Property<string>("Payload")
                        .HasColumnType("longtext");
                    b.Property<string>("Rota")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");
                    b.Property<int>("StatusCode")
                        .HasColumnType("int");
                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("char(36)");
                    b.Property<string>("UsuarioNome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");
                    b.HasKey("Id");
                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("API_NFSe.Domain.Entities.BilhetagemLancamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");
                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);
                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime(6)");
                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");
                    b.Property<string>("Observacao")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");
                    b.Property<Guid>("PrestadorId")
                        .HasColumnType("char(36)");
                    b.Property<int>("Quantidade")
                        .HasColumnType("int");
                    b.Property<int>("SaldoAnterior")
                        .HasColumnType("int");
                    b.Property<int>("SaldoPosterior")
                        .HasColumnType("int");
                    b.Property<Guid>("UsuarioResponsavelId")
                        .HasColumnType("char(36)");
                    b.HasKey("Id");
                    b.HasIndex("PrestadorId");
                    b.ToTable("BilhetagemLancamentos", (string)null);
                });

            modelBuilder.Entity("API_NFSe.Domain.Entities.PrestadorConfiguracao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");
                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");
                    b.Property<Guid>("AtualizadoPorUsuarioId")
                        .HasColumnType("char(36)");
                    b.Property<DateTime?>("CompetenciaSaldo")
                        .HasColumnType("datetime(6)");
                    b.Property<int?>("CreditoMensalPadrao")
                        .HasColumnType("int");
                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime(6)");
                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");
                    b.Property<bool>("EnviaEmailAutomatico")
                        .HasColumnType("tinyint(1)");
                    b.Property<Guid>("PrestadorId")
                        .HasColumnType("char(36)");
                    b.Property<int>("SaldoNotasDisponiveis")
                        .HasColumnType("int");
                    b.Property<string>("SmtpFrom")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");
                    b.Property<string>("SmtpFromName")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");
                    b.Property<string>("SmtpHost")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");
                    b.Property<string>("SmtpPasswordEncrypted")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");
                    b.Property<int?>("SmtpPort")
                        .HasColumnType("int");
                    b.Property<string>("SmtpResetPasswordUrl")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");
                    b.Property<bool>("SmtpSecure")
                        .HasColumnType("tinyint(1)");
                    b.Property<string>("SmtpUser")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");
                    b.Property<string>("VersaoAplicacao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");
                    b.HasKey("Id");
                    b.HasIndex("PrestadorId")
                        .IsUnique();
                    b.ToTable("PrestadorConfiguracoes", (string)null);
                });

            modelBuilder.Entity("API_NFSe.Domain.Entities.BilhetagemLancamento", b =>
                {
                    b.HasOne("API_NFSe.Domain.Entities.Prestador", "Prestador")
                        .WithMany("BilhetagemLancamentos")
                        .HasForeignKey("PrestadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                    b.Navigation("Prestador");
                });

            modelBuilder.Entity("API_NFSe.Domain.Entities.Prestador", b =>
                {
                    b.Navigation("BilhetagemLancamentos");
                });
#pragma warning restore 612, 618
        }
    }
}
