// <auto-generated />
using System;
using API_NFSe.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API_NFSe.Infra.Data.Migrations
{
    [DbContext(typeof(ApiContext))]
    partial class ApiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_general_ci")
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("API_NFSe.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset>("DataHora")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Ip")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Metodo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Payload")
                        .HasColumnType("longtext");

                    b.Property<string>("Rota")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<int>("StatusCode")
                        .HasColumnType("int");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("char(36)");

                    b.Property<string>("UsuarioNome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("API_NFSe.Domain.Entities.Dps", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Ambiente")
                        .HasColumnType("int");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("CodigoLocalEmissao")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("varchar(7)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCompetencia")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset?>("DataEnvio")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset>("DataHoraEmissao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset?>("DataRetorno")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DigestValue")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Identificador")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("JsonEntrada")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MensagemErro")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("NumeroDps")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<Guid>("PrestadorId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Protocolo")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Serie")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("TipoEmissao")
                        .HasColumnType("int");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Versao")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)");

                    b.Property<string>("VersaoAplicacao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("XmlAssinado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("PrestadorId", "Identificador")
                        .IsUnique();

                    b.ToTable("Dps", (string)null);
                });

            modelBuilder.Entity("API_NFSe.Domain.Entities.Prestador", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid?>("AtualizadoPorUsuarioId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("varchar(14)");

                    b.Property<Guid>("CriadoPorUsuarioId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("InscricaoEstadual")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("InscricaoMunicipal")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("NomeFantasia")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Website")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("Cnpj")
                        .IsUnique();

                    b.ToTable("Prestadores", (string)null);
                });

            modelBuilder.Entity("API_NFSe.Domain.Entities.PrestadorCertificado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<Guid>("AtualizadoPorUsuarioId")
                        .HasColumnType("char(36)");

                    b.Property<string>("CaminhoRelativo")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("varchar(260)")
                        .HasColumnName("DadosCertificado");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("varchar(14)");

                    b.Property<string>("CommonName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataEnvio")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataValidade")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("HashConteudo")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<DateTime>("NotAfter")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("NotBefore")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("PrestadorId")
                        .HasColumnType("char(36)");

                    b.Property<string>("SenhaProtegida")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<long>("TamanhoBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("Thumbprint")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("TipoArmazenamento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Alias");

                    b.HasIndex("CaminhoRelativo")
                        .IsUnique();

                    b.HasIndex("Thumbprint")
                        .IsUnique();

                    b.HasIndex("PrestadorId", "Cnpj", "Thumbprint")
                        .IsUnique();

                    b.ToTable("PrestadorCertificados", (string)null);
                });

            modelBuilder.Entity("API_NFSe.Domain.Entities.PrestadorConfiguracao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("AtualizadoPorUsuarioId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("EnviaEmailAutomatico")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("CompetenciaSaldo")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CreditoMensalPadrao")
                        .HasColumnType("int");

                    b.Property<Guid>("PrestadorId")
                        .HasColumnType("char(36)");

                    b.Property<string>("SmtpFrom")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("SmtpFromName")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("SmtpHost")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("SmtpPasswordEncrypted")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<int?>("SmtpPort")
                        .HasColumnType("int");

                    b.Property<string>("SmtpResetPasswordUrl")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("SmtpSecure")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SmtpUser")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("SaldoNotasDisponiveis")
                        .HasColumnType("int");

                    b.Property<string>("VersaoAplicacao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("PrestadorId")
                        .IsUnique();

                    b.ToTable("PrestadorConfiguracoes", (string)null);
                });

            modelBuilder.Entity("API_NFSe.Domain.Entities.RobotClient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<Guid>("PrestadorId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Scopes")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("SecretHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .IsUnique();

                    b.HasIndex("PrestadorId");

                    b.ToTable("RobotClients", (string)null);
                });

            modelBuilder.Entity("API_NFSe.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EmailEncrypted")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<string>("EmailHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<DateTime?>("MfaCodeExpiraEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("MfaCodeHash")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NomeEncrypted")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<Guid?>("PrestadorId")
                        .HasColumnType("char(36)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("RefreshTokenExpiraEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ResetToken")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime?>("ResetTokenExpiraEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("EmailHash")
                        .IsUnique();

                    b.HasIndex("PrestadorId");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("API_NFSe.Domain.Entities.BilhetagemLancamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Observacao")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<Guid>("PrestadorId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<int>("SaldoAnterior")
                        .HasColumnType("int");

                    b.Property<int>("SaldoPosterior")
                        .HasColumnType("int");

                    b.Property<Guid>("UsuarioResponsavelId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("PrestadorId");

                    b.ToTable("BilhetagemLancamentos", (string)null);
                });

            modelBuilder.Entity("API_NFSe.Domain.Entities.BilhetagemLancamento", b =>
                {
                    b.HasOne("API_NFSe.Domain.Entities.Prestador", "Prestador")
                        .WithMany("BilhetagemLancamentos")
                        .HasForeignKey("PrestadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Prestador");
                });

            modelBuilder.Entity("API_NFSe.Domain.Entities.Prestador", b =>
                {
                    b.HasOne("API_NFSe.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("AtualizadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("API_NFSe.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("API_NFSe.Domain.Entities.Usuario", null)
                        .WithMany("BilhetagemLancamentos")
                        .HasForeignKey("PrestadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("API_NFSe.Domain.Entities.Dps", b =>
                {
                    b.HasOne("API_NFSe.Domain.Entities.Prestador", "Prestador")
                        .WithMany("Dps")
                        .HasForeignKey("PrestadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("API_NFSe.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("API_NFSe.Domain.ValueObjects.DpsRegimeTributario", "RegimeTributario", b1 =>
                        {
                            b1.Property<Guid>("DpsId")
                                .HasColumnType("char(36)");

                            b1.Property<int>("OptanteSimplesNacional")
                                .HasColumnType("int");

                            b1.Property<int>("RegimeEspecial")
                                .HasColumnType("int");

                            b1.HasKey("DpsId");

                            b1.ToTable("Dps");

                            b1.WithOwner()
                                .HasForeignKey("DpsId");
                        });

                    b.OwnsOne("API_NFSe.Domain.ValueObjects.DpsServico", "Servico", b1 =>
                        {
                            b1.Property<Guid>("DpsId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("CodigoLocalPrestacao")
                                .IsRequired()
                                .HasMaxLength(7)
                                .HasColumnType("varchar(7)");

                            b1.Property<string>("CodigoTributacaoMunicipal")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("varchar(10)");

                            b1.Property<string>("CodigoTributacaoNacional")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("varchar(10)");

                            b1.Property<string>("DescricaoServico")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("varchar(255)");

                            b1.Property<string>("InformacoesComplementares")
                                .HasMaxLength(1024)
                                .HasColumnType("varchar(1024)");

                            b1.HasKey("DpsId");

                            b1.ToTable("Dps");

                            b1.WithOwner()
                                .HasForeignKey("DpsId");
                        });

                    b.OwnsOne("API_NFSe.Domain.ValueObjects.DpsTomador", "Tomador", b1 =>
                        {
                            b1.Property<Guid>("DpsId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("Documento")
                                .IsRequired()
                                .HasMaxLength(14)
                                .HasColumnType("varchar(14)");

                            b1.Property<string>("Email")
                                .HasMaxLength(120)
                                .HasColumnType("varchar(120)");

                            b1.Property<string>("Nome")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("varchar(150)");

                            b1.Property<string>("Telefone")
                                .HasMaxLength(20)
                                .HasColumnType("varchar(20)");

                            b1.Property<string>("TipoDocumento")
                                .IsRequired()
                                .HasMaxLength(5)
                                .HasColumnType("varchar(5)");

                            b1.HasKey("DpsId");

                            b1.ToTable("Dps");

                            b1.WithOwner()
                                .HasForeignKey("DpsId");

                            b1.OwnsOne("API_NFSe.Domain.ValueObjects.Endereco", "Endereco", b2 =>
                                {
                                    b2.Property<Guid>("DpsTomadorDpsId")
                                        .HasColumnType("char(36)");

                                    b2.Property<string>("Bairro")
                                        .IsRequired()
                                        .HasMaxLength(80)
                                        .HasColumnType("varchar(80)");

                                    b2.Property<string>("Cep")
                                        .HasMaxLength(8)
                                        .HasColumnType("varchar(8)");

                                    b2.Property<string>("CodigoMunicipioIbge")
                                        .IsRequired()
                                        .HasMaxLength(7)
                                        .HasColumnType("varchar(7)");

                                    b2.Property<string>("Complemento")
                                        .HasMaxLength(100)
                                        .HasColumnType("varchar(100)");

                                    b2.Property<string>("Logradouro")
                                        .IsRequired()
                                        .HasMaxLength(150)
                                        .HasColumnType("varchar(150)");

                                    b2.Property<string>("Numero")
                                        .IsRequired()
                                        .HasMaxLength(10)
                                        .HasColumnType("varchar(10)");

                                    b2.Property<string>("Uf")
                                        .HasMaxLength(2)
                                        .HasColumnType("varchar(2)");

                                    b2.HasKey("DpsTomadorDpsId");

                                    b2.ToTable("Dps");

                                    b2.WithOwner()
                                        .HasForeignKey("DpsTomadorDpsId");
                                });

                            b1.Navigation("Endereco")
                                .IsRequired();
                        });

                    b.OwnsOne("API_NFSe.Domain.ValueObjects.DpsValores", "Valores", b1 =>
                        {
                            b1.Property<Guid>("DpsId")
                                .HasColumnType("char(36)");

                            b1.Property<decimal>("ValorServico")
                                .HasColumnType("decimal(18,2)");

                            b1.HasKey("DpsId");

                            b1.ToTable("Dps");

                            b1.WithOwner()
                                .HasForeignKey("DpsId");

                            b1.OwnsOne("API_NFSe.Domain.ValueObjects.DpsTributos", "Tributos", b2 =>
                                {
                                    b2.Property<Guid>("DpsValoresDpsId")
                                        .HasColumnType("char(36)");

                                    b2.Property<int>("IssRetido")
                                        .HasColumnType("int");

                                    b2.Property<int>("TipoRetencaoIss")
                                        .HasColumnType("int");

                                    b2.HasKey("DpsValoresDpsId");

                                    b2.ToTable("Dps");

                                    b2.WithOwner()
                                        .HasForeignKey("DpsValoresDpsId");

                                    b2.OwnsOne("API_NFSe.Domain.ValueObjects.DpsTributosTotais", "Totais", b3 =>
                                        {
                                            b3.Property<Guid>("DpsTributosDpsValoresDpsId")
                                                .HasColumnType("char(36)");

                                            b3.Property<decimal>("Estadual")
                                                .HasColumnType("decimal(18,2)");

                                            b3.Property<decimal>("Federal")
                                                .HasColumnType("decimal(18,2)");

                                            b3.Property<decimal>("Municipal")
                                                .HasColumnType("decimal(18,2)");

                                            b3.HasKey("DpsTributosDpsValoresDpsId");

                                            b3.ToTable("Dps");

                                            b3.WithOwner()
                                                .HasForeignKey("DpsTributosDpsValoresDpsId");
                                        });

                                    b2.Navigation("Totais")
                                        .IsRequired();
                                });

                            b1.Navigation("Tributos")
                                .IsRequired();
                        });

                    b.Navigation("Prestador");

                    b.Navigation("RegimeTributario")
                        .IsRequired();

                    b.Navigation("Servico")
                        .IsRequired();

                    b.Navigation("Tomador")
                        .IsRequired();

                    b.Navigation("Usuario");

                    b.Navigation("Valores")
                        .IsRequired();
                });

            modelBuilder.Entity("API_NFSe.Domain.Entities.Prestador", b =>
                {
                    b.OwnsOne("API_NFSe.Domain.ValueObjects.Endereco", "Endereco", b1 =>
                        {
                            b1.Property<Guid>("PrestadorId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("Bairro")
                                .IsRequired()
                                .HasMaxLength(80)
                                .HasColumnType("varchar(80)");

                            b1.Property<string>("Cep")
                                .HasMaxLength(8)
                                .HasColumnType("varchar(8)");

                            b1.Property<string>("CodigoMunicipioIbge")
                                .IsRequired()
                                .HasMaxLength(7)
                                .HasColumnType("varchar(7)");

                            b1.Property<string>("Complemento")
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)");

                            b1.Property<string>("Logradouro")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("varchar(150)");

                            b1.Property<string>("Numero")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("varchar(10)");

                            b1.Property<string>("Uf")
                                .HasMaxLength(2)
                                .HasColumnType("varchar(2)");

                            b1.HasKey("PrestadorId");

                            b1.ToTable("Prestadores");

                            b1.WithOwner()
                                .HasForeignKey("PrestadorId");
                        });

                    b.Navigation("Endereco")
                        .IsRequired();
                });

            modelBuilder.Entity("API_NFSe.Domain.Entities.PrestadorCertificado", b =>
                {
                    b.HasOne("API_NFSe.Domain.Entities.Prestador", "Prestador")
                        .WithMany("Certificados")
                        .HasForeignKey("PrestadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Prestador");
                });

            modelBuilder.Entity("API_NFSe.Domain.Entities.PrestadorConfiguracao", b =>
                {
                    b.HasOne("API_NFSe.Domain.Entities.Prestador", "Prestador")
                        .WithOne("Configuracao")
                        .HasForeignKey("API_NFSe.Domain.Entities.PrestadorConfiguracao", "PrestadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Prestador");
                });

            modelBuilder.Entity("API_NFSe.Domain.Entities.RobotClient", b =>
                {
                    b.HasOne("API_NFSe.Domain.Entities.Prestador", "Prestador")
                        .WithMany("RobotClients")
                        .HasForeignKey("PrestadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Prestador");
                });

            modelBuilder.Entity("API_NFSe.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("API_NFSe.Domain.Entities.Prestador", "Prestador")
                        .WithMany("Usuarios")
                        .HasForeignKey("PrestadorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Prestador");
                });

            modelBuilder.Entity("API_NFSe.Domain.Entities.Prestador", b =>
                {
                    b.Navigation("Certificados");

                    b.Navigation("Configuracao");

                    b.Navigation("Dps");

                    b.Navigation("RobotClients");

                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
