// Este arquivo contém o array de erros extraído da imagem, pronto para ser usado no seed.ts
const erros = [
  { codigo: 1, mensagem: 'Assinatura do Hash não confere', motivo: 'Reenvie asssinatura do Hash conforme algoritmo estabelecido no Manual de Instrução da NFS-e' },
  { codigo: 2, mensagem: 'Data de competência superior a de emissão do RPS ou da Nota', motivo: 'Informe uma data de competência inferior ou igual a de emissão do RPS ou da Nota.' },
  { codigo: 3, mensagem: 'Natureza da operação não informada.', motivo: 'Utilize um dos tipos: 01 – Tributação no municipio; 02 – Tributação fora do municipio; 03 – Isenção; 04 – Imune; 05 – Exigibilidade suspensa por decisão judicial; 06 – Exigibilidade suspensa por procedimento administrativo.' },
  { codigo: 4, mensagem: 'Esse RPS não foi enviado para a nossa base de dados', motivo: 'Envie o RPS para emissão da NFS-e.' },
  { codigo: 5, mensagem: 'O número da NFS-E substituída informado não existe na base de dados do município.', motivo: 'Informe um número de NFS-E substituída que já tenha sido  emitida.' },
  { codigo: 7, mensagem: 'Essa NFS-e já foi substituída', motivo: 'Confira e informe novamente os dados da NFS-e que deseja substituir.' },
  { codigo: 8, mensagem: 'Campo de  optante pelo simples nacional não informado', motivo: 'Utilize um dos tipos: 1 – Sim; 2 - Não.' },
  { codigo: 9, mensagem: 'Campo de incentivador cultural não informado', motivo: 'Utilize um dos tipos: 1 – Sim; 2 - Não.' },
  { codigo: 10, mensagem: 'RPS já informado.', motivo: 'Para essa Inscrição Municipal/CNPJ já existe um RPS informado com o mesmo número, série e tipo.' },
  { codigo: 11, mensagem: 'Número do RPS não informado', motivo: 'Informe o número do RPS' },
  { codigo: 12, mensagem: 'Tipo do RPS  não informado', motivo: 'Informe o tipo do RPS' },
  { codigo: 14, mensagem: 'Data da emissão do RPS não informada', motivo: 'Informe a Data da emissão do RPS  no formato Date' },
  { codigo: 15, mensagem: 'Data da emissão do RPS inválida', motivo: 'Informe a Data da emissão do RPS  no formato Date' },
  { codigo: 16, mensagem: 'A data da emissão do RPS não poderá ser superior a data de hoje', motivo: 'Informe uma data de emissão de RPS válida' },
  { codigo: 17, mensagem: 'A data da emissão do RPS não poderá ser inferior à data de habilitação do prestador para emissão da NFS-e.', motivo: 'Informe uma data de emissão de RPS válida' },
  { codigo: 18, mensagem: 'O valor dos serviços deverá ser superior a R$ 0,00 (zero)', motivo: 'Não é permitido envio de valor de serviços igual a zero.' },
  { codigo: 19, mensagem: 'O valor das deduções deverá ser inferior ou igual ao valor dos serviços', motivo: 'Não é permitido valor de dedução superior ao valor de serviços.' },
  { codigo: 20, mensagem: 'O valor das deduções deverá ser superior ou igual a R$ 0,00 (zero)', motivo: 'Não é permitido valor de dedução inferior a zero (negativo).' },
  { codigo: 21, mensagem: 'O valor dos descontos deverá ser inferior ou igual ao valor dos serviços', motivo: 'Não é permitido valor de desconto superior ao valor de serviços.' },
  { codigo: 22, mensagem: 'O valor dos descontos deverá ser superior ou igual a R$ 0,00 (zero)', motivo: 'Não é permitido valor de desconto inferior a zero (negativo).' },
  { codigo: 23, mensagem: 'O valor do PIS deverá ser superior ou igual a R$ 0,00 (zero)', motivo: 'Não é permitido valor de retenção inferior a zero (negativo).' },
  { codigo: 24, mensagem: 'O valor da Cofins deverá ser superior ou igual a R$ 0,00 (zero)', motivo: 'Não é permitido valor de retenção inferior a zero (negativo).' },
  { codigo: 25, mensagem: 'O valor do INSS deverá ser superior ou igual a R$ 0,00 (zero)', motivo: 'Não é permitido valor de retenção inferior a zero (negativo).' },
  { codigo: 26, mensagem: 'O valor do IR deverá ser superior ou igual a R$ 0,00 (zero)', motivo: 'Não é permitido valor de retenção inferior a zero (negativo).' },
  { codigo: 27, mensagem: 'O valor da CSLL deverá ser superior ou igual a R$ 0,00 (zero)', motivo: 'Não é permitido valor de retenção inferior a zero (negativo).' },
  { codigo: 30, mensagem: 'Item da lista de serviço inexistente', motivo: 'Consulte a legislação vigente para saber o item da lista de serviço que deverá ser informado neste campo.' },
  { codigo: 31, mensagem: 'Item da lista de serviço não informado para a operação', motivo: 'Informe o item relativo ao serviço prestado nessa operação.' },
  { codigo: 34, mensagem: 'Código de tributação informado é incompatível com a informação de optante pelo simples nacional', motivo: 'Consulte a legislação vigente para saber se o código informado permite a opção pelo simples nacional.' },
  { codigo: 35, mensagem: 'Código de tributação inexistente', motivo: 'Consulte a legislação vigente para saber o Código de tributação que deverá ser informado neste campo.' },
  { codigo: 36, mensagem: 'Campo ISSRetido inválido.', motivo: 'Utilize um dos tipos: 1 para ISS Retido ou 2 para ISS não Retido.' },
  { codigo: 37, mensagem: 'Apenas serviços tributados, no município ou fora, podem sofrer retenção de ISS', motivo: 'Operações isentas, imunes ou com exigibilidade suspensa por decisão judicial ou procedimento administrativo não podem sofrer retenção de ISS.' },
  { codigo: 38, mensagem: 'Contribuintes enquadrados como MEI do simples nacional, Microempresa Municipal, Estimativa, Sociedade de Profissionais ou Incentivador Cultural não podem sofrer retenção de ISS.', motivo: 'Não faça a retenção do ISS nos casos de empresas enquadradas como  MEI do simples nacional, Microempresa Municipal, Estimativa, Sociedade de Profissionais ou Incentivador Cultural.' },
  { codigo: 39, mensagem: 'Apenas empresas tomadoras de serviços inscritas neste municipio podem efetuar retenção de ISS.', motivo: 'O CNPJ e/ou a Inscrição Municipal informada do tomador não foi encontrada na base de dados do município, não sendo permitida a retenção. Acerte o CNPJ e/ou Inscrição Municipal ou altere o campo ISS Retido para 2 (Sem retenção de ISS).' },
  { codigo: 40, mensagem: 'Valor do ISS retido não informado.', motivo: 'O valor do ISS retido deve ser informado quando o campo "IssRetido" for marcado com 1- Sim.' },
  { codigo: 41, mensagem: 'O campo discriminação dos serviços não foi preenchido.', motivo: 'O preenchimento da discriminação dos serviços é obrigatório por lei, devendo ser preenchido adequadamente.' },
  { codigo: 42, mensagem: 'Código do município da prestação do serviço inválido', motivo: 'Consulte a tabela do IBGE e utilize um dos tipos listados na tabela' },
  { codigo: 43, mensagem: 'Inscrição Municipal do prestador não encontrada na base de dados  do município.', motivo: 'Informe a  inscrição municipal correta do prestador.' },
  { codigo: 44, mensagem: 'CNPJ do prestador inválido', motivo: 'Informe o número do CNPJ correto do prestador.' },
  { codigo: 45, mensagem: 'CNPJ não encontrado na base de dados', motivo: 'Confira o numero do CNPJ informado. Caso esteja correto, o prestador não está inscrito no município.' },
  { codigo: 46, mensagem: 'CNPJ do prestador não informado', motivo: 'Informe o CNPJ do prestador.' },
  { codigo: 47, mensagem: 'CPF/CNPJ do tomador inválido', motivo: 'Informe o CPF/CNPJ correto do tomador.' },
  { codigo: 49, mensagem: 'Lote de RPS com excesso de inconsistências.', motivo: 'O serviço de validação de RPS é abortado quando atinge o número de 50 inconsistências. Corrija os erros e reenvie o lote de RPS.' },
  { codigo: 50, mensagem: 'Inscricao Municipal do pretador inválida', motivo: 'Informe a inscricao municipal correta do prestador.' },
  { codigo: 51, mensagem: 'Inscricao Municipal do tomador inválida', motivo: 'Informe a inscricao municipal correta do tomador.' },
  { codigo: 52, mensagem: 'O tomador de serviços informado é o próprio prestador.', motivo: 'Na emissão da NFS-e não é permitido que o prestador seja igual ao tomador.' },
  { codigo: 53, mensagem: 'O campo Inscrição Municipal do tomador só deverá ser preenchido para tomadores estabelecidos neste município', motivo: 'Para tomadores estabelecidos fora deste município não preencher inscrição municipal.' },
  { codigo: 54, mensagem: 'CNPJ do tomador (<CNPJ enviado>) está vinculado a mais de uma inscrição municipal.', motivo: '' },
  { codigo: 60, mensagem: 'A cidade do tomador informada não foi encontrada na base de dados da prefeitura.', motivo: 'Informe a cidade correta do tomador. No caso de cidade do exterior (fora do país), informe o campo com 99999.' },
  { codigo: 61, mensagem: 'Sigla da UF do tomador não corresponde ao CEP informado', motivo: 'Corrija a sigla da UF ou o CEP do tomador do serviço' },
  { codigo: 62, mensagem: 'Cep não existe na tabela DNE dos Correios.', motivo: 'Informar o Cep correto' },
  { codigo: 63, mensagem: 'Razao social do intermediário do serviço não informada com CNPJ/CPF ou Inscrição Municipal do intermediário informada.', motivo: 'Informe a razao social do intermediário do serviço' },
  { codigo: 64, mensagem: 'Inscrição Municipal do intermediário do serviço inválida', motivo: 'Informe a Inscrição Municipal correta do intermediário do serviço.' },
  { codigo: 65, mensagem: 'Inscrição Municipal do intermediário do serviço não esta vinculada ao CNPJ/CPF informado.', motivo: 'Acerte a Inscrição Municipal ou o CNPJ/CPF do intermediário do serviço.' },
  { codigo: 66, mensagem: 'CNPJ/CPF do Intermediario do Serviço invalido', motivo: 'Informe o CNPJ/CPF correto do intermediario do serviço.' },
  { codigo: 69, mensagem: 'Quantidade de RPS incorreta', motivo: 'Informe a quantidade de RPS correta' },
  { codigo: 70, mensagem: 'Inscrição Municipal do prestador especificada no lote não confere com o prestador informado no RPS.', motivo: 'Informe corretamente a Inscrição Municipal do prestador no lote e no RPS.' },
  { codigo: 71, mensagem: 'RPS em duplicidade no arquivo enviado.', motivo: 'Remova do arquivo o registro de RPS excedente.' },
  { codigo: 72, mensagem: 'Campo Quantidade de RPS informado incorretamente.', motivo: 'O campo quantidade de RPS é numérico e deverá ter tamanho máximo de 4 dígitos.' },
  { codigo: 77, mensagem: 'Número da NFS-e não informado', motivo: 'Informe o número da NFS-e.' },
  { codigo: 78, mensagem: 'Número da NFS-e inexistente na base de dados para o prestador de serviço pesquisado', motivo: 'Informe o número correto da NFS-e.' },
  { codigo: 79, mensagem: 'Essa NFS-e já está cancelada', motivo: 'Confira e informe novamente os dados da NFS-e que deseja cancelar.' },
  { codigo: 83, mensagem: 'Campo Inscrição Municipal do tomador informado incorretamente', motivo: 'O campo Inscrição Municipal do tomador é numérico e deverá ter tamanho máximo de 15 dígitos.' },
  { codigo: 84, mensagem: 'Pesquisa pelo cep só pode ser feita com a indicação de uma atividade', motivo: 'Informe uma atividade.' },
  { codigo: 85, mensagem: 'Pesquisa pelo bairro só pode ser feita com a indicação de uma atividade', motivo: 'Informe uma atividade.' },
  { codigo: 86, mensagem: 'Número do protocolo de recebimento do lote inexistente na base de dados', motivo: 'Confira se o lote foi enviado e informe o número correto do protocolo de recebimento.' },
  { codigo: 88, mensagem: 'Número de lote não informado', motivo: 'Informe o número do lote.' },
  { codigo: 89, mensagem: 'Não existe na base de dados uma NFS-e emitida para o número de RPS informado', motivo: 'Informe o número correto do RPS.' },
  { codigo: 92, mensagem: 'Esse RPS foi enviado para a nossa base de dados, mas ainda não foi processado', motivo: 'Faça uma nova consulta mais tarde.' },
  { codigo: 94, mensagem: 'Data de competência não informada.', motivo: 'Informe a data de competência no formato data.' },
  { codigo: 95, mensagem: 'Data de competência informada incorretamente.', motivo: 'Informe a data de competência no formato data.' },
  { codigo: 96, mensagem: 'Campo número do RPS informado incorretamente', motivo: 'O campo Número do RPS é númerico e deverá ter tamanho máximo de 15 dígitos.' },
  { codigo: 97, mensagem: 'Campo série do RPS informado incorretamente', motivo: 'O campo Série do RPS é alfa-númerico e deverá ter tamanho máximo de 5 caracteres.' },
  { codigo: 98, mensagem: 'Valor dos serviços não informado.', motivo: 'Informe o valor dos serviços.' },
  { codigo: 99, mensagem: 'Valor da retenção deverá ser inferior ou igual ao valor dos serviços', motivo: 'Não é permitido valor de retenção superior ao valor de serviços.' },
  { codigo: 100, mensagem: 'Campo valor dos serviços informado incorretamente', motivo: 'O campo valor dos serviços é númerico e deverá ter tamanho máximo de 15,2, ou seja, 15 números inteiros e dois decimais.' },
  { codigo: 101, mensagem: 'Campo deduções informado incorretamente', motivo: 'O campo valor das deduções é númerico e deverá ter tamanho máximo de 15,2, ou seja, 15 números inteiros e dois decimais.' },
  { codigo: 102, mensagem: 'Campo descontos informado incorretamente', motivo: 'O campo valor dos descontos é númerico e deverá ter tamanho máximo de 15,2, ou seja, 15 números inteiros e dois decimais.' },
  { codigo: 104, mensagem: 'Campo item da lista de serviço informado incorretamente', motivo: 'O campo item da lista de serviço deverá ter tamanho máximo de 4 caracteres.' },
  { codigo: 106, mensagem: 'Campo código de tributação do município informado incorretamente', motivo: 'O campo código de tributação do município deverá ter tamanho máximo de 20 caracteres.' },
  { codigo: 107, mensagem: 'Campo discriminação do serviço informado incorretamente.', motivo: 'O campo discriminação do serviço deverá ter tamanho máximo de 2000 caracteres.' },
  { codigo: 108, mensagem: 'Campo município da prestação do serviço informado incorretamente.', motivo: 'O campo município da prestação do serviço deverá ter tamanho máximo de 7 dígitos.' },
  { codigo: 109, mensagem: 'Campo cidade do tomador informado incorretamente.', motivo: 'O campo cidade do tomador deverá ter tamanho máximo de 7 dígitos, consulte tabela do IBGE..' },
  { codigo: 110, mensagem: 'Quando a natureza da operação for tributação fora do município, o campo município da prestação do serviço deverá ser diferente do município do prestador', motivo: 'Informar o município da prestação do serviço corretamente.' },
  { codigo: 111, mensagem: 'Município da prestação do serviço não informado.', motivo: 'Informe o município da prestação do serviço, de acordo com a tabela do IBGE.' },
  { codigo: 112, mensagem: 'Campo Inscrição Municipal do intermediario informado incorretamente', motivo: 'O campo Inscrição Municipal do intermediario é numérico e deverá ter tamanho máximo de 15 dígitos.' },
  { codigo: 116, mensagem: 'A UF do tomador informada não foi encontrada na base de dados.', motivo: 'Informe a UF correta do tomador. Em caso de cidades do exterior (fora do país), preencher a UF com "EX" e a cidade do tomador com 99999.' },
  { codigo: 117, mensagem: 'Campo razão social do tomador informado incorretamente.', motivo: 'O campo razão social do tomador deverá ter tamanho máximo de 115 caracteres.' },
  { codigo: 119, mensagem: 'Campo endereço do tomador informado incorretamente.', motivo: 'O campo endereço do tomador deverá ter tamanho máximo de 125 caracteres.' },
  { codigo: 120, mensagem: 'Campo número do endereço do tomador informado incorretamente.', motivo: 'O campo número do endereço do tomador deverá ter tamanho máximo de 10 caracteres.' },
  { codigo: 121, mensagem: 'Campo complemento do endereço do tomador informado incorretamente.', motivo: 'O campo complemento do endereço do tomador deverá ter tamanho máximo de 60 caracteres.' },
  { codigo: 122, mensagem: 'Campo bairro do tomador informado incorretamente.', motivo: 'O campo bairro do tomador deverá ter tamanho máximo de 60 caracteres.' },
  { codigo: 123, mensagem: 'Campo AliquotaServicos não informado para tributação fora do município.', motivo: 'Informe a aliquota do ISS quando a tributação for fora do município' },
  { codigo: 124, mensagem: 'Campo UF do tomador informado incorretamente.', motivo: 'O campo UF do tomador deverá ter tamanho máximo de 2 caracteres.' },
  { codigo: 125, mensagem: 'Campo CEP do tomador informado incorretamente.', motivo: 'O campo CEP do tomador deverá ter tamanho máximo de 8 dígitos.' },
  { codigo: 126, mensagem: 'Campo e-mail do tomador informado incorretamente.', motivo: 'O campo e-mail do tomador deverá ter tamanho máximo de 80 caracteres.' },
  { codigo: 127, mensagem: 'Campo telefone do tomador informado incorretamente.', motivo: 'O campo telefone do tomador deverá ter tamanho máximo de 11 caracteres.' },
  { codigo: 128, mensagem: 'Campo razão social do intermediário do serviço informado incorretamente.', motivo: 'O campo razão social do intermediário do serviço deverá ter tamanho máximo de 115 caracteres.' },
  { codigo: 129, mensagem: 'Campo código da obra informado incorretamente.', motivo: 'O campo código da obra deverá ter tamanho máximo de 15 caracteres.' },
  { codigo: 130, mensagem: 'Campo ART informado incorretamente.', motivo: 'O campo ART deverá ter tamanho máximo de 15 caracteres.' },
  { codigo: 131, mensagem: 'Campo data inicial preenchido incorretamente', motivo: 'A data informada deverá estar no formato DD/MM/AAAA, ou seja, dia (2 dígitos), seguido de mês (2 dígitos) e ano (4 dígitos)  e deve ser uma data válida.' },
  { codigo: 132, mensagem: 'Campo data final preenchido incorretamente', motivo: 'A data informada deverá estar no formato DD/MM/AAAA, ou seja, dia (2 dígitos), seguido de mês (2 dígitos) e ano (4 dígitos)  e deve ser uma data válida.' },
  { codigo: 133, mensagem: 'Data final da pesquisa não poderá ser supeiror a data de hoje.', motivo: 'Informe uma data final igual ou anterior a data de hoje' },
  { codigo: 134, mensagem: 'A data final não poderá ser anterior à data inicial', motivo: 'Informe uma data final igual ou superior a data inicial da pesquisa' },
  { codigo: 135, mensagem: 'O período de pesquisa não poderá ser superior a um ano.', motivo: 'Limitar as datas de início e final a um período de um ano' },
  { codigo: 136, mensagem: 'Campo número da NFS-e informado incorretamente', motivo: 'O campo número da NFS-e é númerico e deverá ter tamanho máximo de 15 dígitos.' },
  { codigo: 137, mensagem: 'Data de emissão da NFS-e informada incorretamente', motivo: 'Informe a data correta da emissão da NFS-e a ser consultada.' },
  { codigo: 138, mensagem: 'CNPJ não autorizado a realizar o serviço', motivo: 'Informe o CNPJ autorizado a executar o serviço.' },
  { codigo: 139, mensagem: 'Campo número da NFS-e substituída informado incorretamente', motivo: 'O campo número da NFS-e substituída é númerico e deverá ter tamanho máximo de 15 dígitos.' },
  { codigo: 141, mensagem: 'Inscrição Municipal do prestador não informada', motivo: 'informe a Inscrição Municipal do prestador.' },
  { codigo: 142, mensagem: 'Inscrição Municipal do prestador não está vinculada ao CNPJ informado.', motivo: 'Acerte a Inscrição Municipal ou o CNPJ do prestador.' },
  { codigo: 143, mensagem: 'Inscrição Municipal do tomador não está vinculada ao CNPJ informado.', motivo: 'Acerte a Inscrição Municipal ou o CNPJ do tomador.' },
  { codigo: 144, mensagem: 'Natureza da operação inválida.', motivo: 'Utilize um dos tipos: 01 – Tributação no municipio; 02 – Tributação fora do municipio; 03 – Isenção; 04 – Imune; 05 – Exigibilidade suspensa por decisão judicial; 06 – Exigibilidade suspensa por procedimento administrativo.' },
  { codigo: 145, mensagem: 'Regime Especial de Tributação inválido.', motivo: 'Utilize um dos tipos: 01 - Microempresa Municipal; 02 – Estimativa; 03 – Sociedade de Profissionais; 04 – Cooperativa; 05 -  MEI do simples nacional; 06 - ME ou EPP do simples nacional.' },
  { codigo: 146, mensagem: 'Informação de  optante pelo simples nacional inválida.', motivo: 'Utilize um dos tipos: 1 – Sim; 2 - Não.' },
  { codigo: 147, mensagem: 'informação de incentivador cultural inválida.', motivo: 'Utilize um dos tipos: 1 – Sim; 2 - Não.' },
  { codigo: 149, mensagem: 'Campo CNPJPrestador informado incorretamente', motivo: 'O campo CNPJPrestador é númerico e deverá ter tamanho máximo de 14 dígitos.' },
  { codigo: 150, mensagem: 'Série do RPS não informada', motivo: 'Campo de preenchimento obrigatório, caso não utilize série, preencha o campo com 00000.' },
  { codigo: 151, mensagem: 'Quantidade de RPS não informada', motivo: 'Informe a quantidade de RPS.' },
  { codigo: 152, mensagem: 'Campo ISSRetido não informado.', motivo: 'Informe um dos tipos: 1 para ISS Retido ou 2 para ISS não Retido.' },
  { codigo: 153, mensagem: 'Campo ValorISSRetido informado incorretamente', motivo: 'O campo ValorISSRetido é númerico e deverá ter tamanho máximo de 15,2, ou seja, 15 números inteiros e dois decimais.' },
  { codigo: 154, mensagem: 'Campo CNPJ/CPF do Intermediario do Serviço informado incorretamente', motivo: 'O campo CNPJ/CPF do Intermediario do Serviço é númerico e deverá ter tamanho máximo de 14 dígitos.' },
  { codigo: 155, mensagem: 'Campo CPFCNPJTomador informado incorretamente', motivo: 'O campo CPFCNPJTomador é númerico e deverá ter tamanho máximo de 14 dígitos.' },
  { codigo: 156, mensagem: 'CNPJ do prestador não autorizado a emitir NFS-e', motivo: 'Solicite autorização para emitir NFS-e para o CNPJ informado.' },
  { codigo: 157, mensagem: 'Usuário não está autorizado a utilizar esse serviço para esse contribuinte.', motivo: 'Solicite ao contribuinte autorização para utilizar o serviço em seu nome.' },
  { codigo: 158, mensagem: 'Campo Inscrição Municipal do prestador informado incorretamente', motivo: 'O campo Inscrição Municipal do prestador é numérico e deverá ter tamanho máximo de 15 dígitos.' },
  { codigo: 159, mensagem: 'CNPJ do prestador especificado no lote não confere com o prestador informado no RPS.', motivo: 'Informe corretamente o CNPJ do prestador no lote e no RPS.' },
  { codigo: 160, mensagem: 'Arquivo enviado fora da estrutura do arquivo XML de entrada.', motivo: 'Envie um arquivo dentro do schema do arquivo XML de entrada.' },
  { codigo: 161, mensagem: 'Campo ValorISS não informado para tributação fora do município.', motivo: 'Informe o valor do ISS quando a tributação for fora do município' },
  { codigo: 162, mensagem: 'Alíquota do ISS de ME ou EPP do simples nacional informada incorretamente', motivo: 'A alíquota do ISS de ME ou EPP do simoles nacional deve ficar entre 2% e 5%, conforme enquadramento na tabela de receita do simples nacional.' },
  { codigo: 163, mensagem: 'Campo AliquotaServicos não informado para ME ou EPP do simples nacional com retenção do ISS.', motivo: 'Informe a aliquota do ISS de acordo com o enquadramento da ME ou EPP na tabela de receita do simples nacional.' },
  { codigo: 164, mensagem: 'Campo ValorISS informado incorretamente.', motivo: 'O campo ValorISS é númerico e deverá ter tamanho máximo de 15,2, ou seja, 15 números inteiros e dois decimais.' },
  { codigo: 165, mensagem: 'Campo AliquotaServicos informado incorretamente', motivo: 'O campo AliquotaServicos é númerico e deverá ter tamanho máximo de 5,2, ou seja, 5 números inteiros e dois decimais..' },
  { codigo: 166, mensagem: 'Campo RegimeEspecialTributação não informado para empresa optante do simples nacional..', motivo: 'Quando se tratar de empresa optante do simples nacional marcar o campo RegimeEspecialTributação com uma das opções: 05 -  MEI do simples nacional ou  06 - ME ou EPP do simples nacional.' },
  { codigo: 167, mensagem: 'Campo IndicaçãoCPFCNPJ não informado', motivo: 'Utilize um dos tipos: 1 – CPF; 2 - CNPJ; 3 - Não informado.' },
  { codigo: 168, mensagem: 'Campo IndicaçãoCPFCNPJ informado incorretamente.', motivo: 'O Campo  IndicaçãoCPFCNPJ é numérico, com tamanho maximo de 1 dígito e deverá ser utilizado um dos tipos:: 1 – CPF; 2 - CNPJ; 3 - Não informado.' },
  { codigo: 169, mensagem: 'Município informado não pertence à Unidade Federativa.', motivo: 'Acerte o município ou a Unidade Federartiva.' },
  { codigo: 170, mensagem: 'Campo Cep do tomador não deve ser preenchido para tomador do exterior.', motivo: 'Deixe o campo Cep do tomador em branco em caso de tomador do exterior.' },
  { codigo: 171, mensagem: 'Campo CPF/CNPJ do tomador não deve ser preenchido para tomador do exterior.', motivo: 'Deixe o campo CPF/CNPJ do tomador em branco em caso de tomador do exterior.' },
  { codigo: 172, mensagem: 'O documento que realizou a assinatura do lote de RPS não possui autorização para realizar esse serviço.', motivo: 'Acerte a assinatura do lote do RPS.' },
  { codigo: 173, mensagem: 'O documento que realizou a assinatura do RPS não possui autorização para realizar esse serviço.', motivo: 'Acerte a assinatura do RPS.' },
  { codigo: 174, mensagem: 'Arquivo enviado com erro na assinatura.', motivo: 'Acerte a assinatura do arquivo.' },
  { codigo: 175, mensagem: 'Lote sem assinatura.', motivo: 'Assine o lote de RPS' },
  { codigo: 176, mensagem: 'RPS sem assinatura.', motivo: 'Assine o  RPS' },
  { codigo: 177, mensagem: 'O somatório das deduções e do desconto incondicionado está maior que o valor dos serviços', motivo: 'O somatório das deduções e do desconto incondicionado deverá ser inferior ou igual ao valor dos serviços' },
  { codigo: 178, mensagem: 'O somatório dos descontos, retenções federais e ISS retido na fonte está maior que o valor dos serviços', motivo: 'O somatório dos descontos, retenções federais e ISS retido na fonte deverá ser inferior ou igual ao valor dos serviços' },
  { codigo: 179, mensagem: 'Pessoa Física não pode efetuar a retenção do ISSQN', motivo: 'Acerte o campo do ISS retido ou do tomador do serviço.' },
  { codigo: 180, mensagem: ' O lote foi recebido mas não foi processado.', motivo: 'Aguarde para fazer a consulta novamente.' },
  { codigo: 181, mensagem: ' O documento XML de entrada do serviço está fora do padrão', motivo: 'Acerte o arquivo de acordo com o XML Schema especificado.' },
  { codigo: 182, mensagem: 'Erro na autenticação.', motivo: 'O usuário correspondente ao documento utilizado para autenticação não possui autorização para realizar o serviço para a empresa parametrizada via CNPJ e inscrição municipal do arquivo.' },
  { codigo: 183, mensagem: 'Pedido de Cancelamento não está assinado.', motivo: 'O documento XML de dados de pedido de cancelamento não está assinado digitalmente.' },
  { codigo: 184, mensagem: 'E-mail do tomador de serviços inválido', motivo: 'Utilize um E-mail no formato válido.' },
  { codigo: 185, mensagem: 'Telefone do tomador de serviços inválido', motivo: 'Utilize um Telefone no formato válido.' },
  { codigo: 186, mensagem: 'A data de emissão do RPS não pode ser inferior à data de autorização da empresa para geração de NFS-e.', motivo: 'A geração de NFS-e só é permitida para competência superior à data de autorização da empresa. Não utilize competências anteriores à essa data.' },
  { codigo: 187, mensagem: 'Requisição não está acompanhada da autenticação via certificação digital.', motivo: 'É necessário efetuar o processo de autenticação SSL bidirecional no sistema cliente.' },
  { codigo: 188, mensagem: 'O documento XML do cabeçalho de dados esta fora do padrao especificado.', motivo: 'Acerte o arquivo de acordo com o XML Schema especificado.' },
  { codigo: 189, mensagem: 'A versão de dados não é mais suportada pelo sistema.', motivo: 'Utilize uma versão de dados suportada para requisição dos serviços.' },
  { codigo: 190, mensagem: 'A versão de dados não existe.', motivo: 'Utilize uma versão de dados existente e suportada pelo sistema.' },
  { codigo: 191, mensagem: 'Requisição inválida. Não conseguiu capturar o parâmetro nfseCabecMsg e/ou nfseDadosMsg.', motivo: 'Verifique sua mensagem SOAP e a passagem desses parâmetros necessários.' },
  { codigo: 192, mensagem: 'A versão do cabeçalho não existe.', motivo: 'Utilize uma versão de dados suportada para requisição dos serviços.' },
  { codigo: 193, mensagem: 'Campo de optante pelo simples nacional informado como 2(Não) para RegimeEspecialTributacao igual a 5(MEI do Simples Nacional) ou 6 (ME ou EPP do Simples Nacional).', motivo: 'Quando se tratar de empresa com Regime Especial de Tributação 05 -  MEI do simples nacional ou  06 - ME ou EPP do simples nacional marcar campo de Optante pelo Simples como 1 – SIM.' },
  { codigo: 194, mensagem: 'Para Natureza de Operação <Tributação no Município> o município da prestação deverá ser <Belo Horizonte>.', motivo: 'Selecione o município de prestação do serviço como <Belo Horizonte>.' },
  { codigo: 195, mensagem: 'Arquivo enviado com erro de certificado.', motivo: 'Verifique se seu certificado usado no processo de assinatura é válido, ou seja, deve ser pertencente à ICP-Brasil, não estar revogado ou expirado.' },
  { codigo: 196, mensagem: 'Erro de Certificado.', motivo: 'Verifique se seu certificado usado no processo de autenticação é válido, ou seja, deve ser pertencente à ICP-Brasil, não estar revogado ou expirado.' },
];

module.exports = { erros };
